apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-website-final
  template:
    metadata:
      labels:
        app: static-website-final
    spec:
      containers:
      - name: static-website-final
        image: usecasefinal.azurecr.io/myrepo/usecase-img:18
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
