apiVersion: v1
kind: Service
metadata:
  name: static-website-service-final
spec:
  selector:
    app: static-website-final
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer